### ISSUE TITLE
Dig deeper finds empty forward trajectory files

### ISSUE THREAD

**Issue by ntimms718** [lvotapka/openseekr#3]
Here is the error I get:
 python dig_deeper.py 0 /home/ntimms/hsp90SEEKR/seekr_calc.pickle last up  
Parse arguments
Loading SEEKR calculation.
Attempting to extract the last frame of a successful downward trajectory.
Writing new structures and files needed to run umbrella simulation on the lower milestone (milestone 1)
Extracting frame from file: /home/ntimms/hsp90SEEKR/anchor_0_0_0_35.3_29.2_33.3/md/fwd_rev/forward11_0_29.dcd
dcdplugin) read_dcdheader: premature end of file
Traceback (most recent call last):
  File "dig_deeper.py", line 248, in <module>
    last_fwd_frame = seekr.load_last_mdtraj_frame(downward_dcd, prmtop)
  File "/home/ntimms/openseekr/bin/umbrella.py", line 34, in load_last_mdtraj_frame
    for frame in mytraj_iter:
  File "/home/ntimms/miniconda2/envs/SEEKR/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 504, in iterload
    else open(filename))(filename) as f:
  File "/home/ntimms/miniconda2/envs/SEEKR/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 504, in <lambda>
    else open(filename))(filename) as f:
  File "/home/ntimms/miniconda2/envs/SEEKR/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 255, in open
    return loader(filename, mode=mode, force_overwrite=force_overwrite, **kwargs)
  File "mdtraj/formats/dcd/dcd.pyx", line 221, in mdtraj.formats.dcd.DCDTrajectoryFile.__cinit__
IOError: Could not open file: /home/ntimms/hsp90SEEKR/anchor_0_0_0_35.3_29.2_33.3/md/fwd_rev/forward11_0_29.dcd

When I look at the size of the forward trajectory dcd file it is empty.

**Comment by lvotapka** [comment]
Thanks, I am working on this issue now...

**Comment by lvotapka** [comment]
This issue was caused when DCD files are empty, dig_deeper.py now reads a PDB file written at the successful completion of every forward stage, so empty dcds should no longer be a problem.
